name: Deploy Next.js Project

on:
  push:
    branches:
      - master # Đặt branch mà bạn muốn trigger workflow này

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '21'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Another Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.YOUR_PAT_SECRET }}
          publish_dir: ./build # Đường dẫn tới thư mục build của Next.js
